config/routes.rb
Rails.application.routes.draw do

  get 'about' => 'pages#about', as: 'about'
  get 'opportunities' => 'pages#opportunities', as: 'opportunities'
  get 'success' => 'pages#success', as: 'success'

  root 'pages#index', as: 'home'

  get 'designers' => 'users#index', as: 'designers'
  get 'profile' => 'users#show'
  get 'signup' => 'users#new'
  get 'edit' => 'users#edit'
  get 'apply' => 'users#apply', as: 'apply'
  put 'apply' => 'users#update'
  resources :users

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :sessions

  get 'gallery' => 'images#index', as: 'gallery'
  resources :images

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :pic
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  def designer?
    self.privilege > 0 && self.privilege < 4
  end

  def accepted_designer?
    self.privilege == 2
  end

  def accepted_designer_or_admin?
    self.privilege == 2 || self.privilege == 4
  end

  def admin?
    self.privilege == 4
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_non_user
    redirect_to '/' unless !current_user
  end

  def require_user
    redirect_to '/login' unless current_user
  end

  def require_designer
    redirect_to '/' unless (current_user && current_user.designer?)
  end

  def require_accepted_designer
    redirect_to '/' unless (current_user && current_user.accepted_designer?)
  end

  def require_accepted_designer_or_admin
    redirect_to '/' unless (current_user && current_user.accepted_designer_or_admin?)
  end

  def require_admin
    redirect_to '/' unless (current_user && current_user.admin?)
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:show, :new]
  before_action :require_accepted_designer_or_admin, only: [:new]

  # GET /images
  # GET /images.json
  def index
    @images = Image.all
    @title = 'Gallery'
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @title = 'Upload Image'
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @image }
      else
        format.html { render :new }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @image }
      else
        format.html { render :edit }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def image_params
      params.require(:image).permit(:pic, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
before_action :require_user, only: [:success]

  def index
    if current_user
      @title = 'Welcome, ' + current_user.username
    else
      @title = 'Welcome'
    end
  end

  def about
    @title = 'About Us'
    @content = 'Little blurb mom is going to write'
  end

  def opportunities
    @title = 'Opportunities'
    @content = 'Little blurb mom is going to write'
  end

  def success
    @title = 'Congratulations!'
    @content = 'Your application is under review. Visit your profile page to see your current status.'
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_non_user, only: [:new]

  def new
    @title = 'Log In'
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :require_non_user, only: [:new]
before_action :require_user, only: [:show, :apply]
before_action :require_admin, only: [:index]

def index
  @title = 'All Designers'
  @users = User.all

  @up = 2
  @down = 3
end

def show
  @title = 'My Account'
  @user = current_user
  if @user.privilege == 0
    @role = 'User'
  elsif @user.privilege == 1
    @role = 'Designer - Pending'
  elsif @user.privilege == 2
    @role = 'Designer - Approved'
  elsif @user.privilege == 3
    @role = 'Designer - Rejected'
  elsif @user.privilege == 4
    @role = 'Admin'
  end
end

def new
  @title = 'Sign in'
  @user = User.new
  @privilege = 0
end

def create
  @user = User.new(user_signup_params)
  if @user.save
    session[:user_id] = @user.i
    redirect_to '/'
  else
    redirect_to '/signup'
  end
end

def apply
  @user = current_user
  @privilege = 1

  @title = 'Become a Designer'
  @content = 'Please reach out to apply@keenanproject.com before applying'
end

def edit
  @title = 'Edit Profile'
  @user = current_user
end

def update
  if params[:commit] == "Apply"
    @user = current_user
    if @user.update_attributes(user_update_params)
      redirect_to '/success'
    else
      redirect_to '/apply'
    end
  elsif params[:commit] == "Accept" || params[:commit] == "Reject"
    @user = User.find(params[:id])
    if @user.update_attributes(user_update_params)
      redirect_to designers_path
    else
      redirect_to '/'
    end
  elsif params[:commit] == "Submit Changes"
    @user = current_user
    if @user.update_attributes(user_update_params)
      redirect_to '/profile'
    else
      redirect_to '/edit'
    end
  end
end

private
  def user_signup_params
      params.require(:user).permit(:username, :email, :password, :privilege)
  end

  def user_update_params
      params.require(:user).permit(:username, :email, :password, :privilege)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/images/_form.html.erb
<div class="image_form">
  <div class="container">
    <div class="form">

    <%= form_with(model: image, local: true) do |form| %>
      <% if image.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(image.errors.count, "error") %> prohibited this image from being saved:</h2>

          <ul>
            <% image.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label "Image" %><br>
        <%= form.file_field(:pic) %>
      </div>

      <div class="field">
        <br>
        <%= form.label :description %><br>
        <%= form.text_area(:description, {:class => 'form-control'}) %>
      </div>

      <div class="actions">
        <br>
        <%= form.submit({:class => 'btn btn-primary'}) %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/images/edit.html.erb
<h1>Editing Image</h1>

<%= render 'form', image: @image %>

<%= link_to 'Show', @image %> |
<%= link_to 'Back', images_path %>

app/views/images/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @title %></h1>
<br>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% if current_user && current_user.admin? %>
      <% @images.in_groups_of(5).each do |group| %>
        <div class='row'>
          <tr>
            <% group.each do |image| %>
              <% if image %>
                <td> <%= link_to image_tag(image.pic, style: 'object-fit:cover; width:180px; height:180px'), image %>
                <%= link_to 'Details', image %></td>
              <% end %>
            <% end %>
          </tr>
        </div>
      <% end %>
    <% else %>
      <% @images.in_groups_of(6).each do |group| %>
        <div class='row'>
          <tr>
            <% group.each do |image| %>
              <% if image %>
                <td> <%= image_tag(image.pic, style: 'object-fit:cover; width:175px; height:175px') %></td>
              <% end %>
            <% end %>
          </tr>
        </div>
      <% end %>
    <% end %>

  </tbody>
</table>

<% if current_user && current_user.admin? %>
  <br>
  <%= link_to 'Upload New Image', new_image_path %>
<% end %>

<br>

app/views/images/new.html.erb
<h1><%= @title %></h1>
<br>
<%= render 'form', image: @image %>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<%= image_tag(@image.pic, style: 'object-fit:cover; width:230px; height:230px') %>
<br>
<strong>Description: </strong>
<p><%= @image.description %></p>
<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Delete', @image, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to 'Gallery', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Keenan's Charity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1 class="container navbar-brand"><%= link_to image_tag("logok2.jpg", width: '150px'), home_path %></h1>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item nav-link"><%= link_to "Home", home_path %></li>
        <li class="nav-item nav-link"><%= link_to "Gallery", gallery_path %></li>
        <li class="nav-item nav-link"><%= link_to "Opportunities", opportunities_path %></li>
        <li class="nav-item nav-link"><%= link_to "About", about_path %></li>
        <% if current_user && current_user.admin? %>
          <li class="nav-item nav-link"><%= link_to "Designers", designers_path %></li>
        <% end %>
        <% if current_user && current_user.accepted_designer? %>
          <li class="nav-item nav-link"><%= link_to "Upload", new_image_path %></li>
        <% end %>
      </ul>
    </div>
    <div class="nav pull-right">
        <% if current_user %>
           <ul class="navbar-nav mr-auto">
              <li class="nav-item nav-link"><%= link_to "My Account", profile_path %></</li>
              <li class="nav-item nav-link"><%= link_to "Log Out", logout_path, method: "delete" %></li>
           </ul>
         <% else %>
           <ul class="navbar-nav mr-auto">
              <li class="nav-item nav-link"><%= link_to "Login", 'login' %></li>
              <li class="nav-item nav-link"><%= link_to "Sign Up", 'signup' %></li>
           </ul>
        <% end %>
    </div>
    </nav>
    <div class="jumbotron container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/pages/index.html.erb
<h1><%= @title %></h1>

app/views/pages/opportunities.html.erb
<h1><%= @title %></h1>
<br>
<p><%= @content %></p>
<%= link_to "Become a Designer", apply_path %>

app/views/pages/success.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>
<%= link_to "Return", opportunities_path %>

app/views/users/apply.html.erb
<div class="apply">
  <div class="container">
    <div class="form">
      <h1><%= @title %></h1>
      <p><%= @content %></p>

      <%= form_for(@user) do |f| %>
      <div class="field">
        <%= f.hidden_field(:privilege, value: @privilege) %>
      </div>
      <div class="actions">
        <br>
        <%= f.submit("Apply", {:class => 'btn btn-primary'}) %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="edit">
  <div class="container">
    <div class="form">

    <h1><%= @title %></h1>
    <br>

    <%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field(:username, {:class => 'form-control'}) %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field(:email, {:class => 'form-control'}) %>
    </div>
    <div class="actions">
      <br>
      <%= f.submit("Submit Changes", {:class => 'btn btn-primary'}) %>
    </div>
    <% end %>

    <br>
    <%= link_to "Cancel", profile_path %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="designers">
  <div class="container">
    <h1><%= @title %></h1>
    <br>
    <% @users.each do |user| %>
      <% if user.designer? %>
      <p>Name: <%= user.username %></p>
      <p>Email: <%= user.email %></p>
      <p>Status: <%= user.privilege %></p>
      <%= form_for(user) do |f| %>
      <div class="field">
        <%= f.hidden_field(:privilege, value: @up) %>
      </div>
      <div class="actions">
        <br>
        <%= f.submit("Accept", {:class => 'btn btn-success'}) %>
      </div>
      <% end %>
      <%= form_for(user) do |f| %>
      <div class="field">
        <%= f.hidden_field(:privilege, value: @down) %>
      </div>
      <div class="actions">
        <br>
        <%= f.submit("Reject", {:class => 'btn btn-danger'}) %>
      </div>
      <% end %>
      <hr>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="signup">
  <div class="container">
    <div class="form">

    <h1>Sign up</h1>
    <%= form_for(@user) do |f| %>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field(:username, {:class => 'form-control'}) %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field(:email, {:class => 'form-control'}) %>
    </div>
    <div class="field">
      <%= f.label :password %><br>
      <%= f.password_field(:password, {:class => 'form-control'}) %>
    </div>
    <div class="field">
      <%= f.hidden_field(:privilege, value: @privilege) %>
    </div>
    <div class="actions">
      <br>
      <%= f.submit("Create Account", {:class => 'btn btn-primary'}) %>
    </div>
    <% end %>

    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile">
  <div class="container">
    <h1><%= @title %></h1>
    <br>
    <p>Username: <strong><%= @user.username %></strong><br>
       Role: <strong><%= @role %></strong><br>
       Email: <strong><%= @user.email %></strong></p>
    <%=link_to "Edit Profile", edit_path%>
  </div>
</div>